### PR TITLE
py3k: Use new-style exceptions

### PR DESCRIPTION
**Pull request by kba**
From #114 

* Do not raise strings but proper exceptions
* Use new-style except syntax

Comments on possible imrpovements: https://github.com/tmbdev/ocropy/pull/114#pullrequestreview-3418437

### CODE REVIEW

**Comment by QuLogic** [comment]
This and #155 will conflict with each other.

**Comment by kba** [comment]
Yes, but conflicts easily fixed.

**Comment by zuphilip** [comment]
In another PR we also deal with exceptions: https://github.com/tmbdev/ocropy/pull/154/files#diff-0a7898a0c1927c32daf42e51d098ba7c . Any reason we do the exceptions here and there differently?

**Comment by QuLogic** [comment]
That PR is about refactoring where the custom exceptions are; this one is about fixing the syntax for Python 3.

**Comment by zuphilip** [comment]
Superseeded by #175

**Pull request closed without merging**
