### PR TITLE
Update characters for training

### PR DESCRIPTION
**Pull request by zuphilip**
This is a rebase and extension of https://github.com/tmbdev/ocropy/pull/71 by @denydias.

### CODE REVIEW

**Comment by denydias** [comment]
Looking good to me. Just remember to remove that 'ª' before the final merge.

**Comment by zuphilip** [comment]
I already removed this little superscripted a in https://github.com/tmbdev/ocropy/pull/188/commits/38addd313ad815d2435c0ccf5ec900dcaa0c55a4 which is part of this PR.

**Comment by denydias** [comment]
Oh, sure @zuphilip! Sorry for the noise.

**Comment by zuphilip** [comment]
No problem. I appreciate any checking.

The travis test passed, but that does not include the training. Thus, it would be good to test the training is still working the same or better for Portuguese documents. After that I will merge.

**Comment by zuphilip** [comment]
I successfully tested the training. Good for merging now.

**Comment by zuphilip** [comment]
Thank you very much @denydias !

**Comment by denydias** [comment]
You're more than welcome, @zuphilip! It's a honor to have a small piece of code in this project.

**Pull request merged**
