### PR TITLE
Clean up import statements

### PR DESCRIPTION
**Pull request by zuphilip**
These two import statements were hidden
in the main content below, but already
present in the beginning, i.e. they were
duplicate.

### CODE REVIEW

**Comment by zuphilip** [comment]
Split of from #140

**Comment by zuphilip** [comment]
@kba Feel free to add to this branch more code cleaning commits.

**Comment by zuphilip** [comment]
This looks ready now, right? I think, this should be fine to merge @kba.

**Comment by kba** [comment]
I still have commits removing the `__all__ = ...`  in ocrolib/__init__.py and making the `import *` imports explicit but I'd prefer to test all the tools first. I'll post-pone those until CI and more tests.

**Comment by zuphilip** [comment]
Okay, thank you for the commits here!

You can open a new PR whenever the other commits are ready and tested.

**Pull request merged**
