### PR TITLE
Fix regression in ocropus-gpageseg #251

### PR DESCRIPTION
**Pull request by jze**
I looks as if pylab.find and np.where work slightly different.

### CODE REVIEW

**Comment by amitdo** [comment]
https://github.com/tmbdev/ocropy/commit/a154e6360cd8#diff-0e349d933e2d87621d932d2ae80cf70aL272

**Comment by QuLogic** [comment]
Please do not start using the `pylab` interface again.

**Comment by kba** [comment]
Thanks for reporting and sorry for the regression.

[IIUC](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/mlab.py#L1547-L1550), `pylab.find` does this:

```python
def find(condition):
    "Return the indices where ravel(condition) is true"
    res, = np.nonzero(np.ravel(condition))
    return res
```

Does `s,np.find/np.nonzero(np.ravel,` fix the issue?

**Comment by jze** [comment]
Yes, it also works without pylab.

**Comment by kba** [comment]
LGTM, thank you.

@zuphilip In https://github.com/tmbdev/ocropy/commit/a154e6360cd8e15c8c7cd5c2ce225c0ebed9d424 this was the only place where pylab.find was replaced by np.where, right?

@jze If you provide the source images and CLI invocation, we could add a test to prevent this kind of error in the future

**Comment by stweil** [comment]
> In a154e63 this was the only place where pylab.find was replaced by np.where, right?

Yes.

**Comment by zuphilip** [comment]
Merged. Thank you very much @jze for the work and everybody here for the discussion!

**Pull request merged**
