### PR TITLE
Delete unused lru.py

### PR DESCRIPTION
**Pull request by zuphilip**

### CODE REVIEW

**Comment by kba** [comment]
This one we could actually delete, since it's just a copy of the snippet from http://code.activestate.com/recipes/498245-lru-and-lfu-cache-decorators/.

**Comment by zuphilip** [comment]
First, I wanted to delete completely, but then I saw that there is code in `OLD` which is relying on this `lru.py`: https://github.com/tmbdev/ocropy/search?utf8=%E2%9C%93&q=lru&type= and thus I moved it also to OLD. As you see, these are not strong reasons against deleting completely. To be honest, I have never used any file or code from `OLD` so far...

**Comment by amitdo** [comment]
About the OLD dir. Maybe it should be removed.

Git keeps the history, you know...

**Comment by amitdo** [comment]
'ocropus-sauvola' might be useful. See #210.

Consider moving it back to the root dir. It could be used as an alternative to n
'ocropus-nlbin'.

**Comment by amitdo** [comment]
>but while you can find/retrieve old files in Git if you know how and what to look for, discovering useful deleted code is tedious (e.g. when searching in Github or Google).

You can solve this issue by creating a new 'ocropy-unused' repo and move most of the stuff in 'OLD' dir to this repo.

**Comment by zuphilip** [comment]
Okay, the file is deleted now. @kba ready to merge?

**Pull request merged**
