### PR TITLE
Add a workflow diagram for documentation

### PR DESCRIPTION
**Pull request by zuphilip**
The workflow diagram can be looked as dynamic html page at rawgit, i.e.

https://rawgit.com/zuphilip/ocropy/60c56ac75947bcbb7dcbbba354020aed34c3e9e5/doc/workflow.html

Please let me know of any error or confusion this makes. BTW I am not sure if `ocropus-dewarp` is needed anymore at some steps...

### CODE REVIEW

**Comment by zuphilip** [comment]
CLSTM is missing in the diagram

**Comment by amitdo** [comment]
Very nice!

Maybe hocr-pdf should be marked in different color, because it's external to the ocropy project?

**Comment by zuphilip** [comment]
Please have a look at the new version: https://rawgit.com/zuphilip/ocropy/e806a879d46dd2bdb5cd923c26be91fbc8cd0da6/doc/workflow.html

This looks for me now okay. I think we should document the CLSTM possibilities outside this diagram.

Does someone know if `ocropus-dewarp` is currently used for any scenario/workflow?

**Comment by kba** [comment]
Looks very helpful!

Don't know if this already linked somewhere but there's also this mindmap: https://www.mindmeister.com/192257150/ocropus-overview-published

**Comment by zuphilip** [comment]
> Don't know if this already linked somewhere but there's also this mindmap: https://www.mindmeister.com/192257150/ocropus-overview-published

Thanks, I add the mind map to the wiki page: https://github.com/tmbdev/ocropy/wiki (together with a link to this one here).

**Pull request merged**
